'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

//var UsersVotesSchema = new Schema({uid:String, pollOption:String});

var VotesSchema = new Schema({
	// _id: Number // autogenerated 
	createdBy:String,
 	pollName: String,
  	pollOptions: Array,
  	usersVote: Array //[UsersVotesSchema]  // {uid:_id,pollOption,""}
  	//placeholders: Array
});

module.exports = mongoose.model('Votesreact', VotesSchema);

/*
var childSchema = new Schema({ name: 'string' });

var parentSchema = new Schema({
  children: [childSchema]
})
*/


/*
db.votes.aggregate(    [ {$match:{pollName:"poll 2a"}},    {$unwind:"$usersVote"},     { $group : {   _id : { option: "$usersVote.pollOption" } ,count: { $sum: 1 } }   }    ] )
{ "_id" : { "option" : "option a2" }, "count" : 2 }
{ "_id" : { "option" : "option a1" }, "count" : 1 }
*/